### ISSUE TITLE
v1.0.12 does not work on Purpur-1.20.6

### ISSUE THREAD

**Issue by Dynamic-Gravity** [Imprex-Development/zero-inventory-problems#27]
### Description

I was updating my server from purpur-1.20.4 to 1.20.6. (Note: Purpur-1.21.x builds are not yet considered stable)  I upgraded ZIP from 1.0.10 where it was working to the latest 1.0.12 and had the errors.

### Reproduction Steps

Download latest available build and start the server up

### Expected Behaviour

To not error on startup

### Server Details

Purpur version 1.20.6-2233-ver/1.20.6@0d6766e

### Zero Inventory Problems Version

v1.0.12

### Logs and Configs

https://mclo.gs/6avhVaG

**Comment by NgLoader** [comment]
Can you check if it's working with the [latest artifact build](https://github.com/Imprex-Development/zero-inventory-problems/actions/runs/9676348869/artifacts/1639437563)?

**Comment by Dynamic-Gravity** [comment]
Sorry, I haven't had time to verify. But I trust you. So I'll give it a shot when I get a moment and if there is an issue I'll comment again. Thank you very much :]
