### ISSUE TITLE
ZIP cannot be executed via console...

### ISSUE THREAD

**Issue by pokislikisobran** [Imprex-Development/zero-inventory-problems#31]
### Description

I crated a npc shop where players can buy backpacks... But when players click on backpack to buy this message comes in console and players get nothing...

" This command can not be executed from the console "

Command my "npc" is executing: zip give bag %player% 1

### Reproduction Steps

Create a NPC, Make them execute command zip give pokemon %player% 1 , buy the same backpack.

### Expected Behaviour

I hope you can enable somehow in plugin code that command /zip can be executed via console.

### Server Details

Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### Zero Inventory Problems Version

1.0.13

### Logs and Configs

<script src="https://gist.github.com/pokislikisobran/8c16714537c8a8b54a6027c80d8e5d18.js"></script>

**Comment by NgLoader** [comment]
Fixed in 1.0.14
